apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ufteste-net-ca
  namespace: ufteste-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ufteste-net-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server  
  values:
    metadata:
      namespace: ufteste-net
      images:
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
        ca: ghcr.io/hyperledger/bevel-fabric-ca:1.4.8
    deployment:
      annotations:
    annotations:  
      service:
        - example1: example2
      pvc:
 
    server:
      name: ca
      tlsstatus: true
      admin: ufteste-admin 
  
    storage:
      storageclassname: ufteste-bevel-storageclass
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://10.0.2.15:8200
      authpath: localufteste
      secretcert: secretsv2/data/ufteste/peerOrganizations/ufteste-net/ca?ca.ufteste-net-cert.pem
      secretkey: secretsv2/data/ufteste/peerOrganizations/ufteste-net/ca?ufteste-net-CA.key
      secretadminpass: secretsv2/data/ufteste/credentials/ufteste-net/ca/ufteste?user
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          clusteripport: 7054
    proxy:
      provider: none
      type: peer
      external_url_suffix: develop.local.com
