apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ufteste-cacerts-job
  namespace: ufteste-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ufteste-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-cacerts-gen
  values:
    metadata:
      name: ufteste
      component_name: ufteste-net
      namespace: ufteste-net    
      images:
       alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    vault:
      role: vault-role
      address: http://10.0.2.15:8200
      authpath: localufteste
      secretcryptoprefix: secretsv2/data/ufteste/peerOrganizations/ufteste-net/ca
      secretcredentialsprefix: secretsv2/data/ufteste/credentials/ufteste-net/ca/ufteste
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
      
    ca:
      subject: /C=CH/ST=Zurich/L=Zurich/O=Ufteste/CN=ca.ufteste-net
